auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: adminpassword
postgresql:
  enabled: false
externalDatabase:
  host: postgres
  port: 5432
  user: keycloak
  password: supersecret
  database: keycloakdb
service:
  type: NodePort
  nodePorts:
    http: 32080
    https: 32443
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 240
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1
