auth:
  existingSecret: keycloak-admin-secret
  passwordSecretKey: admin-password
  usernameSecretKey: admin-user
externalDatabase:
  host: postgres
  port: 5432
  user: keycloak
  password: supersecret
  database: keycloakdb
postgresql:
  enabled: false # disable bundled PostgreSQL
service:
  type: NodePort
  nodePorts:
    http: 32080
    https: 32443
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
